
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TempAndFanServer
{
    using System.ComponentModel;
    using System.IO.Pipes;
    using System.Security.Cryptography.X509Certificates;
    using System.Text.Json;
    using BlackSharp.Core.Extensions;
    using OpenHardwareMonitor.Hardware;
    using Terminal.Gui;
    using Terminal.Gui.Trees;

    public partial class MainDialog
    {

        public MainDialog()
        {
            InitializeComponent();
            Application.MainLoop.AddTimeout(TimeSpan.FromMilliseconds(100), Update_TimerTick);

            InitScrollableLogView();
            HookWindow(windowStats);
            HookWindow(windowLog);
            HookWindow(windowAbout);

            hardwareMonitor = new HardwareMonitor(ReadHwDescriptor());
            hardwareMonitor.DescriptorChanged+= LogSelectedSensor;

            AddLog("Hardware descriptors:");
            LogSelectedSensor("CPU temp:",hardwareMonitor.CpuTempDescriptor);
            LogSelectedSensor("GPU temp:",hardwareMonitor.GpuTempDescriptor);
            LogSelectedSensor("CPU fan:",hardwareMonitor.CpuFanDescriptor);
            LogSelectedSensor("GPU fan:",hardwareMonitor.GpuFanDescriptor);

            server = new Server();
            server.OnLog += AddLog;
            server.OnGetData += hardwareMonitor.GetStats;
            StartServer(null);

            chkSendFan.Toggled += (b) => { server.ShortFormat = b; };

            PopulateSensorsTree();
            treeSensors.SelectionChanged+= SensorSelected;
            treeSensors.ObjectActivated += ((args) => ShowSensorWindow(false));
            windowSensors.Visible = false;
            windowSensors.Modal = true;

            btnWindowSensorCancel.Clicked += (() => { treeSensors.SelectedObject = null; ShowSensorWindow(false); });
            btnWindowSensorSelect.Clicked += (() => { if (treeSensors.SelectedObject != null) ShowSensorWindow(false); });

            lblCPUTemp.Clicked += (() => SensorLabelClicked(lblCPUTemp));
            lblCPUFan.Clicked += (() => SensorLabelClicked(lblCPUFan));
            lblGPUTemp.Clicked += (() => SensorLabelClicked(lblGPUTemp));
            lblGPUFan.Clicked += (() => SensorLabelClicked(lblGPUFan));
            windowSensors.VisibleChanged += WindowSensorHide;
            txtCPUTemp.Enabled = false;
            txtGPUTemp.Enabled = false;
            txtCpuFan.Enabled = false;
            txtGpuFan.Enabled = false;

            greenOnBlack.Disabled = greenOnBlack.Normal;
            blueOnBlack.Disabled = blueOnBlack.Normal;
            frameDashboard.Border.BorderStyle = BorderStyle.None;
            altDToToggleBetweenDashboardAndFullMode.Action += (() => ShowDashboard(!frameDashboard.Visible));


            lblCPUTemp.Data = ((HardwareMonitor.SensorDescrpitor descriptor) =>
            {
                if (descriptor != null)
                    hardwareMonitor.CpuTempDescriptor = descriptor;
                return hardwareMonitor.CpuTempDescriptor;
            });
            lblGPUTemp.Data = ((HardwareMonitor.SensorDescrpitor descriptor) =>
            {
                if (descriptor != null)
                    hardwareMonitor.GpuTempDescriptor = descriptor;
                return hardwareMonitor.GpuTempDescriptor;
            });
            lblCPUFan.Data = ((HardwareMonitor.SensorDescrpitor descriptor) =>
            {
                if (descriptor != null)
                    hardwareMonitor.CpuFanDescriptor = descriptor;
                return hardwareMonitor.CpuFanDescriptor;
            });
            lblGPUFan.Data = ((HardwareMonitor.SensorDescrpitor descriptor) =>
            {
                if (descriptor != null)
                    hardwareMonitor.GpuFanDescriptor = descriptor;
                return hardwareMonitor.GpuFanDescriptor;
            });
            
            fullViewWindows.Add(windowAbout);
            fullViewWindows.Add(windowSensors);
            fullViewWindows.Add(windowLog);
            fullViewWindows.Add(windowStats);
            ShowDashboard(false);
        }
        List<Window> fullViewWindows = new List<Window>();

        private void ShowDashboard(bool visible = false)
        {
            treeSensors.SelectedObject = null;
            foreach (var window in fullViewWindows)
            {
                if (!visible && window == windowSensors)
                    continue;
                window.Visible = !visible;
            }
            
            frameDashboard.Visible = visible;
            frameDashboard.X = Pos.Center();
            frameDashboard.Y = Pos.Center();            
        }
        private void LogSelectedSensor(string title, HardwareMonitor.SensorDescrpitor descriptor)
        {
            AddLog("  " + title);
            AddLog($"    [{descriptor.HardwareType}|{descriptor.SensorType}|{descriptor.SensorName}]");
        }

        private void WindowSensorHide()
        {
            if (windowSensors.Visible || treeSensors.SelectedObject == null)
                return;
            if (treeSensors.Data is Label l)
            {
                var updater = (l.Data as Func<HardwareMonitor.SensorDescrpitor, HardwareMonitor.SensorDescrpitor>);
                updater(HardwareMonitor.SensorDescrpitor.FromSensor((ISensor)treeSensors.SelectedObject.Tag));
                treeSensors.Data = null;
            }
        }

        void SensorLabelClicked(Label label)
        {
            treeSensors.Data = label;
            SelectSensorInTreeView((label.Data as Func<HardwareMonitor.SensorDescrpitor, HardwareMonitor.SensorDescrpitor>).Invoke(null));
            ShowSensorWindow(true);
        }
        private void SelectSensorInTreeView(HardwareMonitor.SensorDescrpitor descrpitor)
        {
            List<ITreeNode> nodes = new();
            nodes.AddRange(treeSensors.Objects);

            for (int i =0 ;i<nodes.Count();i++)
                nodes.AddRange(nodes[i].Children);

            foreach (var treeNode in nodes)
            {
                if (treeNode.Tag is ISensor sensor
                && sensor.Hardware.HardwareType.ToString() == descrpitor.HardwareType
                && sensor.SensorType.ToString() == descrpitor.SensorType
                && (descrpitor.SensorName == "" || sensor.Name == descrpitor.SensorName))
                {
                    treeSensors.SelectedObject = treeNode;
                    return;
                }
            }

        }

        void ShowSensorWindow(bool visible)
        {
            windowAbout.Enabled = !visible;
            windowStats.Enabled = !visible;
            windowLog.Enabled = !visible;

            windowSensors.Enabled = visible;
            windowSensors.Visible = visible;
            windowSensors.X = Pos.Center();
            windowSensors.Y = Pos.Center();
            if (visible)
            {
                Application.MainLoop.Invoke(() => BringToFront(windowSensors));
                windowSensors.FocusFirst();
            }
        }

        private void SensorSelected(object sender, SelectionChangedEventArgs<ITreeNode> e)
        {
            treeSensors.SelectedObject = e.NewValue;
            treeSensors.ExpandAll();
            treeSensors.EnsureVisible(e.NewValue);
        }

        void PopulateSensorsTree()
        {
            treeSensors.Height = Dim.Fill();
            var hardware = hardwareMonitor.GetAllHardware();

            Dictionary<string,List<string[]>> treeElements =  new();

            treeSensors.RemoveAll();

            foreach(var hw in hardware)
            {
                TreeNode root = new(){Text = hw.HardwareType.ToString()};
                Dictionary<string, TreeNode> typeNodes = new();
                foreach(var sensor in hw.Sensors)
                {
                    AddSensorsToRoot(root, typeNodes, sensor);
                }
                treeSensors.AddObject(root);
                foreach (var subhardware in hw.SubHardware)
                {
                    TreeNode subhwNode =new (){Text = subhardware.HardwareType.ToString()};
                    foreach (var sensor in subhardware.Sensors)
                    {
                        AddSensorsToRoot(subhwNode,typeNodes,sensor);
                    }
                    root.Children.Add(subhwNode);
                }
            }
        }

        private static void AddSensorsToRoot(TreeNode root, Dictionary<string, TreeNode> typeNodes, ISensor sensor)
        {
            if (!typeNodes.TryGetValue(sensor.SensorType.ToString(), out TreeNode typeNode))
            {
                typeNode = new TreeNode() { Text = sensor.SensorType.ToString() };
                root.Children.Add(typeNode);
            }
            typeNode.Children.Add(new TreeNode() { Text = sensor.Name, Tag = sensor });
            typeNodes[sensor.SensorType.ToString()] = typeNode;
        }

        const string hwdescFileName = "hwdesc.json";
        private HardwareMonitor.HardwareDescriptor ReadHwDescriptor()
        {
            string hwdescFileNameFullPath = Path.Combine(
                Path.GetDirectoryName(typeof(MainDialog).Assembly.Location),
                hwdescFileName
                );
            try
            {
                if (HardwareMonitor.HardwareDescriptor.LoadFromFile(hwdescFileNameFullPath, out HardwareMonitor.HardwareDescriptor hardwareDescriptor))
                {
                    return hardwareDescriptor;
                 }
                else
                {
                    AddLog($"Error reading hardware descpriptor {hwdescFileName}, using default one");
                }
            }
            catch
            {
                AddLog($"Exception happend when reading descriptor {hwdescFileName}, using default one");
            }
            return HardwareMonitor.HardwareDescriptor.Default with { FileName = hwdescFileNameFullPath };
        }


        private ScrollBarView CreateScrollBar(ListView view)
        {
            ScrollBarView scrollBar = new ScrollBarView(view, true, true);
            view.Add(scrollBar);

            view.DrawContent += (e) =>
            {
                scrollBar.Size = view.Source.Count;
                scrollBar.Position = view.TopItem;
                scrollBar.Refresh();
            };


            scrollBar.MouseClick += (e) =>
            {
                chkScroll.Checked = false;
            };
            scrollBar.ChangedPosition += () =>
            {
                view.TopItem = scrollBar.Position;
                view.SetNeedsDisplay();
            };
            return scrollBar;
        }
        private void InitScrollableLogView()
        {
            logView.Source = new Terminal.Gui.ListWrapper(LogList);
            logView.Height = Dim.Fill();
            logView.Width = Dim.Fill();

            var scrollBar = CreateScrollBar(logView);

            logView.MouseClick += (e) =>
            {
                chkScroll.Checked = false;
            };

            chkScroll.Toggled += chkScrollToggled;
        }

        private void chkScrollToggled(bool prevState)
        {
            if (!prevState)
                logView.TopItem = Math.Max(0, LogList.Count - 1);
        }

        public bool StartServer(MainLoop loop)
        {
            if (server.Start())
                return false;
            else
            {
                AddLog("Retrying in 3 seconds");
                if (loop == null)
                    Application.MainLoop.AddTimeout(TimeSpan.FromMilliseconds(3000), StartServer);
                return true;                
            }
        }

        private void BringToFront(Window window)
        {
            Remove(window);
            Add(window);

        }
        private void HookWindow(Window window)
        {
            window.Enter += (args) =>
            {
                Application.MainLoop.Invoke(() => BringToFront(window));
            };

            window.MouseClick += (args) =>
            {
                Application.MainLoop.Invoke(() => BringToFront(window));
            };
        }


        readonly Random random = new Random();

        private readonly List<string> LogList  = new List<string>();
        private readonly HardwareMonitor hardwareMonitor;
        private readonly Server server;

        private bool Update_TimerTick(MainLoop loop)
        {
            Application.MainLoop.Invoke(() =>
            {
                UpdateStats(
                    hardwareMonitor.GetStats()
                );
                UpdatedSelectedSensor();
            });
            return true;
        }

        private void UpdatedSelectedSensor()
        {
            if (treeSensors.SelectedObject?.Tag is ISensor sensor)
            {
                sensor.Hardware.Update();
                string unit ="";

                switch(sensor.SensorType )
                {
                    case SensorType.Clock:
                        unit = "MHz";
                        break;
                    case SensorType.Control:
                        unit = "%";
                        break;
                    case SensorType.Load:
                        unit = "%";
                        break;
                    case SensorType.Temperature:
                        unit = "°C";
                        break;
                    case SensorType.Voltage:
                        unit ="V";
                        break;
                    case SensorType.Power:
                        unit = "W";
                        break;
                    case SensorType.Fan:
                        unit = "RPM";
                        break;
                    default:
                        unit = "";
                        break;
                };

                lblSensorValue.Text = $"{(sensor.Value):0.00} {unit}";
            }
            else
            {
                lblSensorValue.Text = "";
            }

        }

        private void UpdateStats(Server.Data data)
        {
            lblCPUTemp.Text = $"{data.CpuTemp:0.00} °C";
            lblCPUFan.Text = $"{data.CpuFan:0.00} %";
            lblGPUTemp.Text = $"{data.GpuTemp:0.00} °C";
            lblGPUFan.Text = $"{data.GpuFan:0.00} %";
            lblFps.Text = $"{data.Fps:0.0}";

            UpdateBigNumbers(txtCPUTemp,data.CpuTemp);
            UpdateBigNumbers(txtGPUTemp,data.GpuTemp);
            txtCpuFan.Text = (ASCIIART.AsciiArt.ConvertRatioToGauge(data.CpuFan / 20.0f, 5));
            txtGpuFan.Text = (ASCIIART.AsciiArt.ConvertRatioToGauge(data.GpuFan / 20.0f, 5));
        }


        private void UpdateBigNumbers(View view, float value)
        {
            view.Text =  ASCIIART.AsciiArt.ConvertFloatToArt(value);
        }

        private void AddLog(string line)
        {
            LogList.Add(line);
           if (chkScroll.Checked)
                logView.TopItem = Math.Max(0, LogList.Count - 1);
        }
    }
}
