
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TempAndFanServer {
    using System;
    using Terminal.Gui;
    
    
    public partial class MainDialog : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.Window windowStats;
        
        private Terminal.Gui.FrameView frameViewCPU;
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.Label lblCPUTemp;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.Label lblCPUFan;
        
        private Terminal.Gui.FrameView frameViewGPU;
        
        private Terminal.Gui.Label label3;
        
        private Terminal.Gui.Label lblGPUTemp;
        
        private Terminal.Gui.Label label4;
        
        private Terminal.Gui.Label lblGPUFan;
        
        private Terminal.Gui.Label label5;
        
        private Terminal.Gui.Label lblFps;
        
        private Terminal.Gui.CheckBox chkSendFan;
        
        private Terminal.Gui.Window windowLog;
        
        private Terminal.Gui.FrameView frameViewLog;
        
        private Terminal.Gui.ListView logView;
        
        private Terminal.Gui.CheckBox chkScroll;
        
        private Terminal.Gui.Window windowAbout;
        
        private Terminal.Gui.Label label7;
        
        private Terminal.Gui.Label label8;
        
        private Terminal.Gui.Window windowSensors;
        
        private Terminal.Gui.FrameView frameView;
        
        private Terminal.Gui.TreeView treeSensors;
        
        private Terminal.Gui.Label label6;
        
        private Terminal.Gui.Label lblSensorValue;
        
        private Terminal.Gui.Button button;
        
        private Terminal.Gui.StatusBar statusBar;
        
        private Terminal.Gui.StatusItem ctrlQToQuit;
        
        private void InitializeComponent() {
            this.statusBar = new Terminal.Gui.StatusBar();
            this.button = new Terminal.Gui.Button();
            this.lblSensorValue = new Terminal.Gui.Label();
            this.label6 = new Terminal.Gui.Label();
            this.treeSensors = new Terminal.Gui.TreeView();
            this.frameView = new Terminal.Gui.FrameView();
            this.windowSensors = new Terminal.Gui.Window();
            this.label8 = new Terminal.Gui.Label();
            this.label7 = new Terminal.Gui.Label();
            this.windowAbout = new Terminal.Gui.Window();
            this.chkScroll = new Terminal.Gui.CheckBox();
            this.logView = new Terminal.Gui.ListView();
            this.frameViewLog = new Terminal.Gui.FrameView();
            this.windowLog = new Terminal.Gui.Window();
            this.chkSendFan = new Terminal.Gui.CheckBox();
            this.lblFps = new Terminal.Gui.Label();
            this.label5 = new Terminal.Gui.Label();
            this.lblGPUFan = new Terminal.Gui.Label();
            this.label4 = new Terminal.Gui.Label();
            this.lblGPUTemp = new Terminal.Gui.Label();
            this.label3 = new Terminal.Gui.Label();
            this.frameViewGPU = new Terminal.Gui.FrameView();
            this.lblCPUFan = new Terminal.Gui.Label();
            this.label2 = new Terminal.Gui.Label();
            this.lblCPUTemp = new Terminal.Gui.Label();
            this.label = new Terminal.Gui.Label();
            this.frameViewCPU = new Terminal.Gui.FrameView();
            this.windowStats = new Terminal.Gui.Window();
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.blueOnBlack = new Terminal.Gui.ColorScheme();
            this.blueOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.blueOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.blueOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.ColorScheme = this.blueOnBlack;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.windowStats.Width = 51;
            this.windowStats.Height = 9;
            this.windowStats.X = 4;
            this.windowStats.Y = 2;
            this.windowStats.Visible = true;
            this.windowStats.ColorScheme = this.blueOnBlack;
            this.windowStats.Modal = false;
            this.windowStats.IsMdiContainer = false;
            this.windowStats.Data = "windowStats";
            this.windowStats.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.windowStats.Border.Effect3D = true;
            this.windowStats.Border.Effect3DBrush = null;
            this.windowStats.Border.DrawMarginFrame = true;
            this.windowStats.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.windowStats.Title = "Stats";
            this.Add(this.windowStats);
            this.frameViewCPU.Width = 24;
            this.frameViewCPU.Height = 6;
            this.frameViewCPU.X = 1;
            this.frameViewCPU.Y = 0;
            this.frameViewCPU.Visible = true;
            this.frameViewCPU.Data = "frameViewCPU";
            this.frameViewCPU.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameViewCPU.Border.Effect3D = false;
            this.frameViewCPU.Border.Effect3DBrush = null;
            this.frameViewCPU.Border.DrawMarginFrame = true;
            this.frameViewCPU.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameViewCPU.Title = "CPU";
            this.windowStats.Add(this.frameViewCPU);
            this.label.Width = 4;
            this.label.Height = 1;
            this.label.X = 0;
            this.label.Y = 0;
            this.label.Visible = true;
            this.label.Data = "label";
            this.label.Text = "Temp :";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameViewCPU.Add(this.label);
            this.lblCPUTemp.Width = 5;
            this.lblCPUTemp.Height = 1;
            this.lblCPUTemp.X = 14;
            this.lblCPUTemp.Y = 0;
            this.lblCPUTemp.Visible = true;
            this.lblCPUTemp.Data = "lblCPUTemp";
            this.lblCPUTemp.Text = "40 °C";
            this.lblCPUTemp.TextAlignment = Terminal.Gui.TextAlignment.Right;
            this.frameViewCPU.Add(this.lblCPUTemp);
            this.label2.Width = 4;
            this.label2.Height = 1;
            this.label2.X = 0;
            this.label2.Y = 2;
            this.label2.Visible = true;
            this.label2.Data = "label2";
            this.label2.Text = "Fan  :";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameViewCPU.Add(this.label2);
            this.lblCPUFan.Width = 4;
            this.lblCPUFan.Height = 1;
            this.lblCPUFan.X = 14;
            this.lblCPUFan.Y = 2;
            this.lblCPUFan.Visible = true;
            this.lblCPUFan.Data = "lblCPUFan";
            this.lblCPUFan.Text = "50 %";
            this.lblCPUFan.TextAlignment = Terminal.Gui.TextAlignment.Right;
            this.frameViewCPU.Add(this.lblCPUFan);
            this.frameViewGPU.Width = 24;
            this.frameViewGPU.Height = 6;
            this.frameViewGPU.X = 25;
            this.frameViewGPU.Y = 0;
            this.frameViewGPU.Visible = true;
            this.frameViewGPU.Data = "frameViewGPU";
            this.frameViewGPU.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameViewGPU.Border.Effect3D = false;
            this.frameViewGPU.Border.Effect3DBrush = null;
            this.frameViewGPU.Border.DrawMarginFrame = true;
            this.frameViewGPU.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameViewGPU.Title = "GPU";
            this.windowStats.Add(this.frameViewGPU);
            this.label3.Width = 4;
            this.label3.Height = 1;
            this.label3.X = 0;
            this.label3.Y = 0;
            this.label3.Visible = true;
            this.label3.Data = "label3";
            this.label3.Text = "Temp :";
            this.label3.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameViewGPU.Add(this.label3);
            this.lblGPUTemp.Width = 5;
            this.lblGPUTemp.Height = 1;
            this.lblGPUTemp.X = 14;
            this.lblGPUTemp.Y = 0;
            this.lblGPUTemp.Visible = true;
            this.lblGPUTemp.Data = "lblGPUTemp";
            this.lblGPUTemp.Text = "40 °C";
            this.lblGPUTemp.TextAlignment = Terminal.Gui.TextAlignment.Right;
            this.frameViewGPU.Add(this.lblGPUTemp);
            this.label4.Width = 4;
            this.label4.Height = 1;
            this.label4.X = 0;
            this.label4.Y = 2;
            this.label4.Visible = true;
            this.label4.Data = "label4";
            this.label4.Text = "Fan :";
            this.label4.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameViewGPU.Add(this.label4);
            this.lblGPUFan.Width = 4;
            this.lblGPUFan.Height = 1;
            this.lblGPUFan.X = 14;
            this.lblGPUFan.Y = 2;
            this.lblGPUFan.Visible = true;
            this.lblGPUFan.Data = "lblGPUFan";
            this.lblGPUFan.Text = "50 %";
            this.lblGPUFan.TextAlignment = Terminal.Gui.TextAlignment.Right;
            this.frameViewGPU.Add(this.lblGPUFan);
            this.label5.Width = 5;
            this.label5.Height = 1;
            this.label5.X = 2;
            this.label5.Y = 6;
            this.label5.Visible = true;
            this.label5.Data = "label5";
            this.label5.Text = "FPS :";
            this.label5.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.windowStats.Add(this.label5);
            this.lblFps.Width = 4;
            this.lblFps.Height = 1;
            this.lblFps.X = 7;
            this.lblFps.Y = 6;
            this.lblFps.Visible = true;
            this.lblFps.Data = "lblFps";
            this.lblFps.Text = "90";
            this.lblFps.TextAlignment = Terminal.Gui.TextAlignment.Right;
            this.windowStats.Add(this.lblFps);
            this.chkSendFan.Width = 6;
            this.chkSendFan.Height = 1;
            this.chkSendFan.X = 24;
            this.chkSendFan.Y = 6;
            this.chkSendFan.Visible = true;
            this.chkSendFan.Data = "chkSendFan";
            this.chkSendFan.Text = "Send Fan speed and fps";
            this.chkSendFan.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.chkSendFan.Checked = true;
            this.windowStats.Add(this.chkSendFan);
            this.windowLog.Width = 69;
            this.windowLog.Height = 17;
            this.windowLog.X = 57;
            this.windowLog.Y = 2;
            this.windowLog.Visible = true;
            this.windowLog.ColorScheme = this.blueOnBlack;
            this.windowLog.Modal = false;
            this.windowLog.IsMdiContainer = false;
            this.windowLog.Data = "windowLog";
            this.windowLog.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.windowLog.Border.Effect3D = true;
            this.windowLog.Border.Effect3DBrush = null;
            this.windowLog.Border.DrawMarginFrame = true;
            this.windowLog.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.windowLog.Title = "Server log";
            this.Add(this.windowLog);
            this.frameViewLog.Width = 67;
            this.frameViewLog.Height = 14;
            this.frameViewLog.X = 0;
            this.frameViewLog.Y = 0;
            this.frameViewLog.Visible = true;
            this.frameViewLog.Data = "frameViewLog";
            this.frameViewLog.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameViewLog.Border.Effect3D = false;
            this.frameViewLog.Border.Effect3DBrush = null;
            this.frameViewLog.Border.DrawMarginFrame = true;
            this.frameViewLog.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameViewLog.Title = "";
            this.windowLog.Add(this.frameViewLog);
            this.logView.Width = 70;
            this.logView.Height = 10;
            this.logView.X = 0;
            this.logView.Y = 0;
            this.logView.Visible = true;
            this.logView.Data = "logView";
            this.logView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.logView.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Server stared on 0.0.0.0:1648",
                        "New connection from (\'192.168.100.26\', 65095)"});
            this.logView.AllowsMarking = false;
            this.logView.AllowsMultipleSelection = true;
            this.frameViewLog.Add(this.logView);
            this.chkScroll.Width = 6;
            this.chkScroll.Height = 1;
            this.chkScroll.X = 59;
            this.chkScroll.Y = 14;
            this.chkScroll.Visible = true;
            this.chkScroll.Data = "chkScroll";
            this.chkScroll.Text = "S_croll";
            this.chkScroll.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.chkScroll.Checked = true;
            this.windowLog.Add(this.chkScroll);
            this.windowAbout.Width = 37;
            this.windowAbout.Height = 4;
            this.windowAbout.X = 11;
            this.windowAbout.Y = 14;
            this.windowAbout.Visible = true;
            this.windowAbout.ColorScheme = this.blueOnBlack;
            this.windowAbout.Modal = false;
            this.windowAbout.IsMdiContainer = false;
            this.windowAbout.Data = "windowAbout";
            this.windowAbout.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.windowAbout.Border.Effect3D = false;
            this.windowAbout.Border.Effect3DBrush = null;
            this.windowAbout.Border.DrawMarginFrame = true;
            this.windowAbout.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.windowAbout.Title = "About";
            this.Add(this.windowAbout);
            this.label7.Width = 4;
            this.label7.Height = 1;
            this.label7.X = 1;
            this.label7.Y = 0;
            this.label7.Visible = true;
            this.label7.Data = "label7";
            this.label7.Text = "TempAndFanServer for Skyloong 4.0";
            this.label7.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.windowAbout.Add(this.label7);
            this.label8.Width = 10;
            this.label8.Height = 1;
            this.label8.X = 2;
            this.label8.Y = 1;
            this.label8.Visible = true;
            this.label8.Data = "label8";
            this.label8.Text = "By Cob_258 (github.com/cobrce)";
            this.label8.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.windowAbout.Add(this.label8);
            this.windowSensors.Width = 88;
            this.windowSensors.Height = 19;
            this.windowSensors.X = 23;
            this.windowSensors.Y = 21;
            this.windowSensors.Visible = true;
            this.windowSensors.ColorScheme = this.greyOnBlack;
            this.windowSensors.Modal = false;
            this.windowSensors.IsMdiContainer = false;
            this.windowSensors.Data = "windowSensors";
            this.windowSensors.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.windowSensors.Border.Effect3D = true;
            this.windowSensors.Border.Effect3DBrush = null;
            this.windowSensors.Border.DrawMarginFrame = true;
            this.windowSensors.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.windowSensors.Title = "Select sensor";
            this.Add(this.windowSensors);
            this.frameView.Width = 86;
            this.frameView.Height = 16;
            this.frameView.X = 0;
            this.frameView.Y = 0;
            this.frameView.Visible = true;
            this.frameView.Data = "frameView";
            this.frameView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameView.Border.Effect3D = false;
            this.frameView.Border.Effect3DBrush = null;
            this.frameView.Border.DrawMarginFrame = true;
            this.frameView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView.Title = "";
            this.windowSensors.Add(this.frameView);
            this.treeSensors.Width = 85;
            this.treeSensors.Height = 15;
            this.treeSensors.X = 0;
            this.treeSensors.Y = 0;
            this.treeSensors.Visible = true;
            this.treeSensors.Data = "treeSensors";
            this.treeSensors.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.treeSensors.Style.CollapseableSymbol = '-';
            this.treeSensors.Style.ColorExpandSymbol = false;
            this.treeSensors.Style.ExpandableSymbol = '+';
            this.treeSensors.Style.InvertExpandSymbolColors = false;
            this.treeSensors.Style.LeaveLastRow = false;
            this.treeSensors.Style.ShowBranchLines = true;
            this.frameView.Add(this.treeSensors);
            this.label6.Width = 14;
            this.label6.Height = 1;
            this.label6.X = 1;
            this.label6.Y = 16;
            this.label6.Visible = true;
            this.label6.Data = "label6";
            this.label6.Text = "Actual value : ";
            this.label6.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.windowSensors.Add(this.label6);
            this.lblSensorValue.Width = 3;
            this.lblSensorValue.Height = 1;
            this.lblSensorValue.X = 16;
            this.lblSensorValue.Y = 16;
            this.lblSensorValue.Visible = true;
            this.lblSensorValue.Data = "lblSensorValue";
            this.lblSensorValue.Text = "";
            this.lblSensorValue.TextAlignment = Terminal.Gui.TextAlignment.Right;
            this.windowSensors.Add(this.lblSensorValue);
            this.button.Width = 8;
            this.button.Height = 1;
            this.button.X = 75;
            this.button.Y = 16;
            this.button.Visible = true;
            this.button.Data = "button";
            this.button.Text = "Cancel";
            this.button.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button.IsDefault = false;
            this.windowSensors.Add(this.button);
            this.statusBar.Width = Dim.Fill(0);
            this.statusBar.Height = 1;
            this.statusBar.X = 0;
            this.statusBar.Y = Pos.AnchorEnd(1);
            this.statusBar.Visible = true;
            this.statusBar.Data = "statusBar";
            this.statusBar.Text = "";
            this.statusBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.ctrlQToQuit = new Terminal.Gui.StatusItem(((Terminal.Gui.Key)(1048588u)), "Ctrl+Q to quit", null);
            this.statusBar.Items = new Terminal.Gui.StatusItem[] {
                    this.ctrlQToQuit};
            this.Add(this.statusBar);
        }
    }
}
