
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TempAndFanServer
{
    using System.IO.Pipes;
    using System.Security.Cryptography.X509Certificates;
    using System.Text.Json;
    using Terminal.Gui;


    public partial class MainDialog
    {

        public MainDialog()
        {
            InitializeComponent();
            Application.MainLoop.AddTimeout(TimeSpan.FromMilliseconds(100), Update_TimerTick);

            InitScrollableLogView();
            HookWindow(windowStats);
            HookWindow(windowLog);
            HookWindow(windowAbout);

            hardwareMonitor = new HardwareMonitor(ReadHwDescriptor());

            server = new Server();
            server.OnLog += AddLog;
            server.OnGetData += hardwareMonitor.GetStats;
            StartServer(null);

            chkSendFan.Toggled += (b) => { server.ShortFormat = b; };
        }

        const string hwdescFileName = "hwdesc.json";
        private HardwareMonitor.HardwareDescriptor ReadHwDescriptor()
        {
            try
            {
                string hwdescFileNameFullPath = Path.Combine(
                    Path.GetDirectoryName(typeof(MainDialog).Assembly.Location),
                    hwdescFileName
                    );
                 if (HardwareMonitor.HardwareDescriptor.LoadFromFile(hwdescFileNameFullPath,  out HardwareMonitor.HardwareDescriptor hardwareDescriptor))
                 {
                    return hardwareDescriptor;
                 }
                else
                {
                    AddLog($"Error reading hardware descpriptor {hwdescFileName}, using default one");
                }
            }
            catch
            {
                AddLog($"Exception happend when reading descriptor {hwdescFileName}, using default one");
            }
            return HardwareMonitor.HardwareDescriptor.Default;
        }

        private void InitScrollableLogView()
        {
            logView.Source = new Terminal.Gui.ListWrapper(LogList);
            logView.Height = Dim.Fill();
            logView.Width = Dim.Fill();

            ScrollBarView scrollBar = new ScrollBarView(logView, true, true);
            frameViewLog.Add(scrollBar);

            scrollBar.MouseClick += (e) =>
            {
                chkScroll.Checked = false;
            };

            logView.MouseClick += (e) =>
            {
                chkScroll.Checked = false;
            };

            scrollBar.ChangedPosition += () =>
            {
                logView.TopItem = scrollBar.Position;
                logView.SetNeedsDisplay();
            };

            logView.DrawContent += (e) =>
            {
                scrollBar.Size = logView.Source.Count - 1;
                scrollBar.Position = logView.TopItem;
                scrollBar.Refresh();
            };
        }


        public bool StartServer(MainLoop loop)
        {
            if (server.Start())
                return false;
            else
            {
                AddLog("Retrying in 3 seconds");
                if (loop == null)
                    Application.MainLoop.AddTimeout(TimeSpan.FromMilliseconds(3000), StartServer);
                return true;                
            }
        }

        private void BringToFront(Window window)
        {
            Remove(window);
            Add(window);

        }
        private void HookWindow(Window window)
        {
            window.Enter += (args) =>
            {
                Application.MainLoop.Invoke(() => BringToFront(window));
            };

            window.MouseClick += (args) =>
            {
                Application.MainLoop.Invoke(() => BringToFront(window));
            };
        }


        readonly Random random = new Random();

        private readonly List<string> LogList  = new List<string>();
        private readonly HardwareMonitor hardwareMonitor;
        private readonly Server server;

        private bool Update_TimerTick(MainLoop loop)
        {
            UpdateStats(
                hardwareMonitor.GetStats()
            );
            return true;
        }

        private void UpdateStats(Server.Data data)
        {
            lblCPUTemp.Text = $"{(int)data.CpuTemp} °C";
            lblCPUFan.Text = $"{(int)data.CpuFan} %";
            lblGPUTemp.Text = $"{(int)data.GpuTemp} °C";
            lblGPUFan.Text = $"{(int)data.GpuFan} %";
            lblFps.Text = $"{(int)data.Fps}";
        }

        private void AddLog(string line)
        {
            LogList.Add(line);
            if (chkScroll.Checked)
                logView.TopItem = Math.Max(0, LogList.Count - 1);
        }
    }
}
