
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace TempAndFanServer
{
    using System.ComponentModel;
    using System.IO.Pipes;
    using System.Security.Cryptography.X509Certificates;
    using System.Text.Json;
    using BlackSharp.Core.Extensions;
    using OpenHardwareMonitor.Hardware;
    using Terminal.Gui;
    using Terminal.Gui.Trees;

    public partial class MainDialog
    {

        public MainDialog()
        {
            InitializeComponent();
            Application.MainLoop.AddTimeout(TimeSpan.FromMilliseconds(100), Update_TimerTick);

            InitScrollableLogView();
            HookWindow(windowStats);
            HookWindow(windowLog);
            HookWindow(windowAbout);

            hardwareMonitor = new HardwareMonitor(ReadHwDescriptor());

            server = new Server();
            server.OnLog += AddLog;
            server.OnGetData += hardwareMonitor.GetStats;
            StartServer(null);

            chkSendFan.Toggled += (b) => { server.ShortFormat = b; };

            PopulateSensorsTree();
            treeSensors.SelectionChanged+= SensorSelected;
            windowSensors.Visible = false;
            windowSensors.Modal = true;

            btnWindowSensorCancel.Clicked += (() => { treeSensors.SelectedObject = null; ShowSensorWindow(false); });
            btnWindowSensorSelect.Clicked += (() => { if (treeSensors.SelectedObject != null) ShowSensorWindow(false); });
            lblCPUTemp.Clicked += SelectCPUTempSensor;
            lblCPUFan.Clicked += SelectCPUFanSensor;
            lblGPUTemp.Clicked += SelectGPUTempSensor;
            lblGPUFan.Clicked += SelectGpuFanSensor;
        }
        

        private void SelectSensorInTreeView(HardwareMonitor.SensorDescrpitor descrpitor)
        {
            List<ITreeNode> nodes = new();
            nodes.AddRange(treeSensors.Objects);

            for (int i =0 ;i<nodes.Count();i++)
                nodes.AddRange(nodes[i].Children);

            foreach (var treeNode in nodes)
            {
                if (treeNode.Tag is ISensor sensor
                && sensor.Hardware.HardwareType.ToString() == descrpitor.HardwareType
                && sensor.SensorType.ToString() == descrpitor.SensorType
                && (descrpitor.SensorName == "" || sensor.Name == descrpitor.SensorName))
                {
                    treeSensors.SelectedObject = treeNode;
                    return;
                }
            }

        }


        // CPU temperature sensor
        private void SelectCPUTempSensor()
        {
            SelectSensorInTreeView(hardwareMonitor.CpuTempDescriptor);
            ShowSensorWindow(true);
            windowSensors.VisibleChanged+= SelectCPUTempSensorEnd;
        }

        private void SelectCPUTempSensorEnd()
        {
            windowSensors.VisibleChanged-= SelectCPUTempSensorEnd;
            if (treeSensors.SelectedObject!=null)
                hardwareMonitor.CpuTempDescriptor = HardwareMonitor.SensorDescrpitor.FromSensor((ISensor)treeSensors.SelectedObject.Tag);
        }

        // CPU fan sensor

        private void SelectCPUFanSensor()
        {
            SelectSensorInTreeView(hardwareMonitor.CpuFanDescriptor);
            ShowSensorWindow(true);
            windowSensors.VisibleChanged+= SelectCPUFanSensorEnd;
        }


        private void SelectCPUFanSensorEnd()
        {
            windowSensors.VisibleChanged-= SelectCPUFanSensorEnd;
            if (treeSensors.SelectedObject!=null)
                hardwareMonitor.CpuFanDescriptor = HardwareMonitor.SensorDescrpitor.FromSensor((ISensor)treeSensors.SelectedObject.Tag);
        }

        // GPU temperature sensor
        private void SelectGPUTempSensor()
        {
            SelectSensorInTreeView(hardwareMonitor.GpuTempDescriptor);
            ShowSensorWindow(true);
            windowSensors.VisibleChanged+= SelectGPUTempSensorEnd;
        }

        private void SelectGPUTempSensorEnd()
        {
            windowSensors.VisibleChanged-= SelectGPUTempSensorEnd;
            if (treeSensors.SelectedObject!=null)
                hardwareMonitor.GpuTempDescriptor = HardwareMonitor.SensorDescrpitor.FromSensor((ISensor)treeSensors.SelectedObject.Tag);
        }

        // GPU fan sensor
        private void SelectGpuFanSensor()
        {
            SelectSensorInTreeView(hardwareMonitor.GpuFanDescriptor);
            ShowSensorWindow(true);
            windowSensors.VisibleChanged+= SelectGpuFanSensorEnd;
        }

        private void SelectGpuFanSensorEnd()
        {
            windowSensors.VisibleChanged-=SelectGpuFanSensorEnd;
            if (treeSensors.SelectedObject!=null)
                hardwareMonitor.GpuFanDescriptor = HardwareMonitor.SensorDescrpitor.FromSensor((ISensor)treeSensors.SelectedObject.Tag);
            ShowSensorWindow(false);
        }

        void ShowSensorWindow(bool visible)
        {
            windowAbout.Enabled = !visible;
            windowStats.Enabled = !visible;
            windowLog.Enabled = !visible;

            windowSensors.Enabled = visible;
            windowSensors.Visible = visible;
            windowSensors.X = Pos.Center();
            windowSensors.Y = Pos.Center();
            if (visible)
            {
                Application.MainLoop.Invoke(() => BringToFront(windowSensors));
                windowSensors.FocusFirst();
            }
        }

        private void SensorSelected(object sender, SelectionChangedEventArgs<ITreeNode> e)
        {
            treeSensors.SelectedObject = e.NewValue;
            treeSensors.ExpandAll();
            treeSensors.EnsureVisible(e.NewValue);
        }

        void PopulateSensorsTree()
        {
            treeSensors.Height = Dim.Fill();
            var hardware = hardwareMonitor.GetAllHardware();

            Dictionary<string,List<string[]>> treeElements =  new();

            treeSensors.RemoveAll();

            foreach(var hw in hardware)
            {
                TreeNode root = new(){Text = hw.HardwareType.ToString()};
                Dictionary<string, TreeNode> typeNodes = new();
                foreach(var sensor in hw.Sensors)
                {
                    AddSensorsToRoot(root, typeNodes, sensor);
                }
                treeSensors.AddObject(root);
                foreach (var subhardware in hw.SubHardware)
                {
                    TreeNode subhwNode =new (){Text = subhardware.HardwareType.ToString()};
                    foreach (var sensor in subhardware.Sensors)
                    {
                        AddSensorsToRoot(subhwNode,typeNodes,sensor);
                    }
                    root.Children.Add(subhwNode);
                }
            }
        }

        private static void AddSensorsToRoot(TreeNode root, Dictionary<string, TreeNode> typeNodes, ISensor sensor)
        {
            if (!typeNodes.TryGetValue(sensor.SensorType.ToString(), out TreeNode typeNode))
            {
                typeNode = new TreeNode() { Text = sensor.SensorType.ToString() };
                root.Children.Add(typeNode);
            }
            typeNode.Children.Add(new TreeNode() { Text = sensor.Name, Tag = sensor });
            typeNodes[sensor.SensorType.ToString()] = typeNode;
        }

        const string hwdescFileName = "hwdesc.json";
        private HardwareMonitor.HardwareDescriptor ReadHwDescriptor()
        {
            string hwdescFileNameFullPath = Path.Combine(
                Path.GetDirectoryName(typeof(MainDialog).Assembly.Location),
                hwdescFileName
                );
            try
            {
                if (HardwareMonitor.HardwareDescriptor.LoadFromFile(hwdescFileNameFullPath, out HardwareMonitor.HardwareDescriptor hardwareDescriptor))
                {
                    return hardwareDescriptor;
                 }
                else
                {
                    AddLog($"Error reading hardware descpriptor {hwdescFileName}, using default one");
                }
            }
            catch
            {
                AddLog($"Exception happend when reading descriptor {hwdescFileName}, using default one");
            }
            return HardwareMonitor.HardwareDescriptor.Default with { FileName = hwdescFileNameFullPath };
        }


        private ScrollBarView CreateScrollBar(View view)
        {
            ScrollBarView scrollBar = new ScrollBarView(logView, true, true);
            view.Add(scrollBar);
            scrollBar.ChangedPosition += () =>
            {
                view.SetNeedsDisplay();
            };

            view.DrawContent += (e) =>
            {
                scrollBar.Size = logView.Source.Count - 1;
                scrollBar.Position = logView.TopItem;
                scrollBar.Refresh();
            };
            return scrollBar;
        }
        private void InitScrollableLogView()
        {
            logView.Source = new Terminal.Gui.ListWrapper(LogList);
            logView.Height = Dim.Fill();
            logView.Width = Dim.Fill();

            var scrollBar = CreateScrollBar(logView);

            scrollBar.MouseClick += (e) =>
            {
                chkScroll.Checked = false;
            };

            logView.MouseClick += (e) =>
            {
                chkScroll.Checked = false;
            };

            scrollBar.ChangedPosition += () =>
            {
                logView.TopItem = scrollBar.Position;
                logView.SetNeedsDisplay();
            };
        }


        public bool StartServer(MainLoop loop)
        {
            if (server.Start())
                return false;
            else
            {
                AddLog("Retrying in 3 seconds");
                if (loop == null)
                    Application.MainLoop.AddTimeout(TimeSpan.FromMilliseconds(3000), StartServer);
                return true;                
            }
        }

        private void BringToFront(Window window)
        {
            Remove(window);
            Add(window);

        }
        private void HookWindow(Window window)
        {
            window.Enter += (args) =>
            {
                Application.MainLoop.Invoke(() => BringToFront(window));
            };

            window.MouseClick += (args) =>
            {
                Application.MainLoop.Invoke(() => BringToFront(window));
            };
        }


        readonly Random random = new Random();

        private readonly List<string> LogList  = new List<string>();
        private readonly HardwareMonitor hardwareMonitor;
        private readonly Server server;

        private bool Update_TimerTick(MainLoop loop)
        {
            Application.MainLoop.Invoke(() =>
            {
                UpdateStats(
                    hardwareMonitor.GetStats()
                );
                UpdatedSelectedSensor();
            });
            return true;
        }

        private void UpdatedSelectedSensor()
        {
            if (treeSensors.SelectedObject?.Tag is ISensor sensor)
            {
                sensor.Hardware.Update();
                string unit ="";

                switch(sensor.SensorType )
                {
                    case SensorType.Clock:
                        unit = "MHz";
                        break;
                    case SensorType.Control:
                        unit = "%";
                        break;
                    case SensorType.Load:
                        unit = "%";
                        break;
                    case SensorType.Temperature:
                        unit = "°C";
                        break;
                    case SensorType.Voltage:
                        unit ="V";
                        break;
                    case SensorType.Power:
                        unit = "W";
                        break;
                    case SensorType.Fan:
                        unit = "RPM";
                        break;
                    default:
                        unit = "";
                        break;
                };

                lblSensorValue.Text = $"{(sensor.Value):0.00} {unit}";
            }
            else
            {
                lblSensorValue.Text = "";
            }

        }

        private void UpdateStats(Server.Data data)
        {
            lblCPUTemp.Text = $"{data.CpuTemp:0.00} °C";
            lblCPUFan.Text = $"{data.CpuFan:0.00} %";
            lblGPUTemp.Text = $"{data.GpuTemp:0.00} °C";
            lblGPUFan.Text = $"{data.GpuFan:0.00} %";
            lblFps.Text = $"{data.Fps:0.0}";
        }

        private void AddLog(string line)
        {
            LogList.Add(line);
            if (chkScroll.Checked)
                logView.TopItem = Math.Max(0, LogList.Count - 1);
        }
    }
}
